def build (bld):
	bld.recurse ('errors')
	bld.recurse ('async')
	bld.recurse ('per-user')

	if bld.env['VALAC']:
		bld.recurse ('vala')

def check (bld):
	bld.recurse ('errors')
	bld.recurse ('async')
	bld.recurse ('per-user')

	if bld.env['VALAC']:
		bld.recurse ('vala')
